---

- name: Render the docker-compose file
  template:
    src: "{{ role_path }}/templates/docker-compose.yml.j2"
    dest: /home/ubuntu/docker-compose.yml
    mode: '0644'
    owner: ubuntu
    group: ubuntu

- name: Copy service
  template:
    src: "{{ role_path }}/templates/cachet.service.j2"
    dest: /etc/systemd/system/cachet.service
    owner: root
    group: root
    mode: 0600

- name: Copy over dockerfile
  synchronize:
    src: "{{ role_path }}/files"
    dest: /home/ubuntu

- name: Enable and start service
  systemd:
    name: cachet
    enabled: yes
    state: started

