- hosts: all
  vars_files:
    - vars/main.yml
  roles:
    - { role: "dev-sec.os-hardening", when: ansible_hardening | default(false) | bool }
    - { role: "dev-sec.ssh-hardening", when: ansible_hardening | default(false) | bool }
    - { role: volumes, when: instance_store_enabled | default(false) | bool }
    - common
    - geerlingguy.nodejs
    - statusfy
