version: 2
jobs:
  test:
    docker:
      - image: insightinfrastructure/terragrunt-aws-ci:v0.5.2
    steps:
      - checkout
      - run:
          name: Copy the config and make configs
          command: |
            aws s3 cp s3://ii-ci-1-configs/icon-monitor.yaml ./config.yaml
            make configs
      - run:
          name: Apply module
          command: |
            ssh-keygen -b 2048 -t rsa -f ./id_rsa -q -N ""
            ./.circleci/test-trigger.sh

workflows:
  version: 2
  default:
    jobs:
      - test:
          context: all-provider-ci-1
