---

- name: Render the docker-compose file
  template:
    src: "{{ role_path }}/templates/docker-compose.yml.j2"
    dest: /home/ubuntu/docker-compose.yml
    mode: '0644'
    owner: ubuntu
    group: ubuntu

- name: Render the config file
  template:
    src: "{{ role_path }}/templates/config.js.j2"
    dest: /home/ubuntu/config.js
    mode: '0644'
    owner: ubuntu
    group: ubuntu

- name: Copy service
  template:
    src: "{{ role_path }}/templates/statusfy.service.j2"
    dest: /etc/systemd/system/statusfy.service
    owner: root
    group: root
    mode: 0600


- name: Enable and start service
  systemd:
    name: statusfy
    enabled: yes
    state: started

